### ISSUE TITLE
 Something about ann_file

### ISSUE THREAD

**Issue by WangYQ999** [ben-z-original/s2ds#2]
Hello author, do you have any JSON or XML annotation files for the s2ds dataset?

**Comment by ben-z-original** [comment]
Nope, sry. 

JSON and XML is often used for instance segmentation datasets, S2DS is semantic segmentation only (no instances). However, perhaps fiftyone is an option for you. Some hassle to import the dataset (custom importer might be needed), but it has a to_detection conversion option and can export the COCO format.
